theme: jekyll-theme-architect
title: Welcome to Alivia's Blog.
description: I write about reinforcement learning and metalearning here. I use personal projects and online MOOCs to power my learning, I am not in a PhD program at the moment.
